# Generated by Django 5.1.4 on 2025-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
    ]
