# Generated by Django 5.1.4 on 2025-04-17 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='questions.question')),
            ],
        ),
    ]
