# Generated by Django 5.1.4 on 2025-04-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_correct_answer_count_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
