# Generated by Django 5.1.4 on 2025-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
