apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quizapp-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
