name: Build and Push to ACR

on:
    workflow_dispatch:
#   push:
#     branches:
#       - main  # or 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/quizapp-app:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/quizapp-app:latest
